### ISSUE TITLE
onVerify callback is not getting called

### ISSUE THREAD

**Issue by kknaidumca** [sarneeh/reaptcha#108]
After successful reaptcha verification onverify callback is not getting called.

**Comment by kknaidumca** [comment]
Resolved

**Comment by enrichit** [comment]
For future googlers and investigators using the "invisible" size of captcha, try turning it off for a second, it's possible you've misconfigured it and the only way to see the error is to see the component, it doesn't appear in the console or anything.

For me it's because I was on localhost and google only allows 127.0.0.1 as a valid domain.

**Comment by sarneeh** [comment]
@kknaidumca If you resolved your issue, share with others what was the issue and how did you solve it - it could help others also :)

@enrichit Thanks for sharing this! :)

**Comment by richardvanbergen** [comment]
@sarneeh Thanks for building this!

**Comment by sarneeh** [comment]
@richardvanbergen You're welcome! :smile:
