### ISSUE TITLE
uncaught (in promise) timeout

### ISSUE THREAD

**Issue by alyrik** [sarneeh/reaptcha#97]
Every time a component containing `<Reaptcha />` is unmounted I get (in 5–10 sec) that annoying error in `recaptcha__en.js:105`. Handlers `onError` and `onExpire` are not called. I tried to call `reset` and `_stopTimer` in `componentWillUnmount` but it didn't help.

I use invisible Recaptcha v2. Actually, when component with `<Reaptcha />` is mounted again after the error, Recaptcha works without problems. So the only problem is that error falling to console and error tracking service.

I also tried several solutions (e.g. [clearing cookies](https://stackoverflow.com/questions/52055847/recaptcha-request-timed-out-in-bootstrap-modal-popup/52056016)) but no one worked. 

Is there any way to avoid it?

**Comment by sarneeh** [comment]
I've played around a little bit with this error and can reproduce it. Unfortunately this is an error in Google's `recaptcha` script, which - for some reason - has the `reset` function delayed and expects the widget to still be available in the DOM (which isn't, because React cleans it up).

There's a workaround for this introduced in [react-google-recaptcha(https://github.com/dozoisch/react-google-recaptcha/pull/120) but I don't really like fixes that add some unclear logic just to get rid of some console error that actually has no impact on the overall functioning.

Unfortunately I don't have much time right now to look for some other solution, but I'd be happy to review any PR's on this. If no one will be willing to take this, I'll take a look at this issue in 1-2 months.

**Comment by Puspendert** [comment]
Hi @sarneeh 
Any update here? I am facing the same.

**Comment by sarneeh** [comment]
@Puspendert No update as I don't have time right now to implement any fix for that. This error is a false-positive so it's not too important. If you really find it annoying feel free to contribute 😉

**Comment by Undistraction** [comment]
@sarneeh useful thread on this on [SO](https://stackoverflow.com/questions/52390562/google-recaptcha-response-uncaught-in-promise-null). 

First answer:

>  I had this error too and I found is related with the recaptcha callback (in your case data-callback="callback"). If you remove your data-callback attribute the error won't come up.
